<?php
/**
 * KycCheckTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ebay\Sell\Account
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Account API
 *
 * The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.
 *
 * OpenAPI spec version: v1.9.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Account;

use PHPUnit\Framework\TestCase;

/**
 * KycCheckTest Class Doc Comment
 *
 * @category    Class
 * @description This type is used to provide details about any KYC check that is applicable to the managed payments seller.
 * @package     Ebay\Sell\Account
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class KycCheckTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "KycCheck"
     */
    public function testKycCheck()
    {
    }

    /**
     * Test attribute "data_required"
     */
    public function testPropertyDataRequired()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "remedy_url"
     */
    public function testPropertyRemedyUrl()
    {
    }

    /**
     * Test attribute "alert"
     */
    public function testPropertyAlert()
    {
    }

    /**
     * Test attribute "detail_message"
     */
    public function testPropertyDetailMessage()
    {
    }
}
