<?php
/**
 * SetReturnPolicyResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Ebay\Sell\Account
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Account API
 *
 * The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.
 *
 * OpenAPI spec version: v1.9.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Ebay\Sell\Account;

use PHPUnit\Framework\TestCase;

/**
 * SetReturnPolicyResponseTest Class Doc Comment
 *
 * @category    Class
 * @description A complex type that is populated with a response containing a return policies.
 * @package     Ebay\Sell\Account
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class SetReturnPolicyResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "SetReturnPolicyResponse"
     */
    public function testSetReturnPolicyResponse()
    {
    }

    /**
     * Test attribute "category_types"
     */
    public function testPropertyCategoryTypes()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "extended_holiday_returns_offered"
     */
    public function testPropertyExtendedHolidayReturnsOffered()
    {
    }

    /**
     * Test attribute "international_override"
     */
    public function testPropertyInternationalOverride()
    {
    }

    /**
     * Test attribute "marketplace_id"
     */
    public function testPropertyMarketplaceId()
    {
    }

    /**
     * Test attribute "name"
     */
    public function testPropertyName()
    {
    }

    /**
     * Test attribute "refund_method"
     */
    public function testPropertyRefundMethod()
    {
    }

    /**
     * Test attribute "restocking_fee_percentage"
     */
    public function testPropertyRestockingFeePercentage()
    {
    }

    /**
     * Test attribute "return_instructions"
     */
    public function testPropertyReturnInstructions()
    {
    }

    /**
     * Test attribute "return_method"
     */
    public function testPropertyReturnMethod()
    {
    }

    /**
     * Test attribute "return_period"
     */
    public function testPropertyReturnPeriod()
    {
    }

    /**
     * Test attribute "return_policy_id"
     */
    public function testPropertyReturnPolicyId()
    {
    }

    /**
     * Test attribute "returns_accepted"
     */
    public function testPropertyReturnsAccepted()
    {
    }

    /**
     * Test attribute "return_shipping_cost_payer"
     */
    public function testPropertyReturnShippingCostPayer()
    {
    }

    /**
     * Test attribute "warnings"
     */
    public function testPropertyWarnings()
    {
    }
}
