<?php
/**
 * ReturnPolicyApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Ebay\Sell\Account
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Account API
 *
 * The <b>Account API</b> gives sellers the ability to configure their eBay seller accounts, including the seller's policies (eBay business policies and seller-defined custom policies), opt in and out of eBay seller programs, configure sales tax tables, and get account information.  <br><br>For details on the availability of the methods in this API, see <a href=\"/api-docs/sell/account/overview.html#requirements\">Account API requirements and restrictions</a>.
 *
 * OpenAPI spec version: v1.9.1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.51
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Ebay\Sell\Account;

use Ebay\Sell\Account\Configuration;
use Ebay\Sell\Account\ApiException;
use Ebay\Sell\Account\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReturnPolicyApiTest Class Doc Comment
 *
 * @category Class
 * @package  Ebay\Sell\Account
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ReturnPolicyApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for createReturnPolicy
     *
     * .
     *
     */
    public function testCreateReturnPolicy()
    {
    }

    /**
     * Test case for deleteReturnPolicy
     *
     * .
     *
     */
    public function testDeleteReturnPolicy()
    {
    }

    /**
     * Test case for getReturnPolicies
     *
     * .
     *
     */
    public function testGetReturnPolicies()
    {
    }

    /**
     * Test case for getReturnPolicy
     *
     * .
     *
     */
    public function testGetReturnPolicy()
    {
    }

    /**
     * Test case for getReturnPolicyByName
     *
     * .
     *
     */
    public function testGetReturnPolicyByName()
    {
    }

    /**
     * Test case for updateReturnPolicy
     *
     * .
     *
     */
    public function testUpdateReturnPolicy()
    {
    }
}
